### ISSUE TITLE
Red alloy based cables could do with giving more when crafting

### ISSUE THREAD

**Issue by skyem123** [CitadelCore/DescentPacks#85]
It feels that they take a ridiculous amount of wool and ends up not being very practical to use since you don't get a lot when crafting it.

Would it be reasonable if one got more out when crafting it? So it's easier for people to make redstone stuff, which will ease automation.

**Comment by ThePiGuy24** [comment]
Yes, its 24 redstone + 3 iron for 12 for red alloy cable, not including the insulated versions, Imo should be 24 because the 3 iron makes up for the cost of the convenience. 

I also think the amount of wool required for insulated versions should be reduced as volumetrically, each (straight) piece of cable uses 128 voxels, or just over 3% of a wool block, meaning that 24 cables (the suggested amount) should only require 75% of a wool block, so it should at most be 1 wool block per 24 cables.

**Comment by ThePiGuy24** [comment]
Making some of the gate cheaper would be nice aswell.

**Comment by skyem123** [comment]
> I also think the amount of wool required for insulated versions should be reduced as volumetrically, each (straight) piece of cable uses 128 voxels, or just over 3% of a wool block, meaning that 24 cables (the suggested amount) should only require 75% of a wool block, so it should at most be 1 wool block per 24 cables.

Shouldn't it be like 1 wool for 32 cables then?
`(16 * 16 * 16) / 128 = 32`
